#!/usr/bin/env bash
# ==========================================================================
# BVL POC — one-command Supabase bootstrap (no dashboard clicking required)
#
# Creates (or links) a Supabase project, applies the schema + centre seed as
# migrations, fetches the API keys, and writes a ready-to-use .env file.
#
# Prerequisites (one-time, in a browser):
#   1. A Supabase account          -> https://supabase.com
#   2. A Personal Access Token     -> https://supabase.com/dashboard/account/tokens
#      Then either run `supabase login` once, or:
#         export SUPABASE_ACCESS_TOKEN=sbp_xxx
#
# Usage:
#   ./setup_supabase.sh                          # interactive: pick or create a project
#   ./setup_supabase.sh --new "BVL Registration" # create a new project
#   ./setup_supabase.sh --link <project-ref>     # use an existing project
#   ./setup_supabase.sh --local                  # run everything locally in Docker
# ==========================================================================
set -euo pipefail

REGION="${SUPABASE_REGION:-ap-south-1}"   # Mumbai — closest to Assam
MODE=""
PROJECT_NAME="BVL Registration"
PROJECT_REF=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    --new)   MODE="new";   [[ -n "${2:-}" && "${2:0:2}" != "--" ]] && { PROJECT_NAME="$2"; shift; } ;;
    --link)  MODE="link";  PROJECT_REF="${2:?--link needs a project ref}"; shift ;;
    --local) MODE="local" ;;
    -h|--help) sed -n '2,22p' "$0"; exit 0 ;;
    *) echo "Unknown option: $1" >&2; exit 1 ;;
  esac
  shift
done

say() { printf '\n\033[1;34m==>\033[0m %s\n' "$*"; }
die() { printf '\n\033[1;31mERROR:\033[0m %s\n' "$*" >&2; exit 1; }

# --------------------------------------------------------------------------
# 0. Check the CLI is installed
# --------------------------------------------------------------------------
if ! command -v supabase >/dev/null 2>&1; then
  cat >&2 <<'EOF'
The Supabase CLI is not installed. Install it with ONE of:

  # Recommended on WSL/Ubuntu — standalone binary, no Node needed:
  curl -fsSL https://github.com/supabase/cli/releases/latest/download/supabase_linux_amd64.tar.gz \
    | tar -xz -C /tmp && sudo mv /tmp/supabase /usr/local/bin/

  # Or via npm (project-local):
  npm install supabase --save-dev     # then use: npx supabase <cmd>

  # Or via Homebrew:
  brew install supabase/tap/supabase
EOF
  exit 1
fi
say "Supabase CLI found: $(supabase --version 2>/dev/null | head -1)"

# --------------------------------------------------------------------------
# 1. Initialise the local project structure (idempotent)
# --------------------------------------------------------------------------
[[ -f supabase/config.toml ]] || { say "Initialising Supabase project files"; supabase init; }

# --------------------------------------------------------------------------
# LOCAL MODE — full stack in Docker, no cloud account at all
# --------------------------------------------------------------------------
if [[ "$MODE" == "local" ]]; then
  say "Starting the local Supabase stack (Docker required — first run pulls ~1GB)"
  supabase start
  say "Applying migrations to the local database"
  supabase db reset            # recreates the local DB and replays every migration

  API_URL="$(supabase status -o env 2>/dev/null | sed -n 's/^API_URL=//p' | tr -d '"')"
  SERVICE_KEY="$(supabase status -o env 2>/dev/null | sed -n 's/^SERVICE_ROLE_KEY=//p' | tr -d '"')"
  cat > .env <<EOF
# Generated by setup_supabase.sh (LOCAL mode) on $(date -Iseconds)
SUPABASE_URL=${API_URL:-http://127.0.0.1:54321}
SUPABASE_SERVICE_KEY=${SERVICE_KEY}

# Fill these in from KoboToolbox:
KOBO_TOKEN=
KOBO_ASSET_UID=
KOBO_BASE_URL=https://kf.kobotoolbox.org
EOF
  say "Done. Local Studio: http://127.0.0.1:54323  ·  credentials written to .env"
  exit 0
fi

# --------------------------------------------------------------------------
# 2. Authenticate
# --------------------------------------------------------------------------
if [[ -z "${SUPABASE_ACCESS_TOKEN:-}" ]]; then
  supabase projects list >/dev/null 2>&1 || {
    say "Not logged in — opening browser login (or set SUPABASE_ACCESS_TOKEN)"
    supabase login
  }
fi

# --------------------------------------------------------------------------
# 3. Create or choose the project
# --------------------------------------------------------------------------
if [[ "$MODE" == "new" ]]; then
  ORG_ID="$(supabase orgs list -o json 2>/dev/null | grep -o '"id"[[:space:]]*:[[:space:]]*"[^"]*"' | head -1 | cut -d'"' -f4)"
  [[ -n "$ORG_ID" ]] || die "Could not determine your organisation id. Run: supabase orgs list"

  DB_PASSWORD="$(head -c 24 /dev/urandom | base64 | tr -d '/+=' | head -c 24)"
  say "Creating project '$PROJECT_NAME' in region $REGION (org $ORG_ID)"
  supabase projects create "$PROJECT_NAME" \
      --org-id "$ORG_ID" --region "$REGION" --db-password "$DB_PASSWORD"

  echo "$DB_PASSWORD" > .db_password
  chmod 600 .db_password
  say "Database password saved to .db_password — keep it, it is not recoverable"

  PROJECT_REF="$(supabase projects list -o json 2>/dev/null \
      | tr ',' '\n' | grep -A2 -i "$PROJECT_NAME" | grep -o '"id"[[:space:]]*:[[:space:]]*"[^"]*"' | head -1 | cut -d'"' -f4)"
  say "Waiting ~60s for the new database to finish provisioning"
  sleep 60
fi

if [[ -z "$PROJECT_REF" ]]; then
  say "Select your project:"
  supabase projects list
  read -rp "Enter the Reference ID of the project to use: " PROJECT_REF
fi
[[ -n "$PROJECT_REF" ]] || die "No project reference supplied."

# --------------------------------------------------------------------------
# 4. Link and push the migrations
# --------------------------------------------------------------------------
say "Linking to project $PROJECT_REF"
supabase link --project-ref "$PROJECT_REF"

say "Pushing migrations (schema + 141 centre seed rows)"
supabase db push

# --------------------------------------------------------------------------
# 5. Fetch keys and write .env
# --------------------------------------------------------------------------
say "Fetching API keys"
KEYS_RAW="$(supabase projects api-keys --project-ref "$PROJECT_REF" -o env 2>/dev/null || true)"

SERVICE_KEY="$(printf '%s' "$KEYS_RAW" | sed -n 's/^SERVICE_ROLE_KEY=//p' | tr -d '"')"
[[ -n "$SERVICE_KEY" ]] || SERVICE_KEY="$(printf '%s' "$KEYS_RAW" | sed -n 's/^SECRET_KEY=//p' | tr -d '"')"

if [[ -z "$SERVICE_KEY" ]]; then
  echo
  supabase projects api-keys --project-ref "$PROJECT_REF" || true
  read -rp "Paste the service_role (or sb_secret_...) key: " SERVICE_KEY
fi

cat > .env <<EOF
# Generated by setup_supabase.sh on $(date -Iseconds)
SUPABASE_URL=https://${PROJECT_REF}.supabase.co
SUPABASE_SERVICE_KEY=${SERVICE_KEY}

# Fill these in from KoboToolbox (Account Settings -> Security -> API key,
# and the a... id in your deployed form's URL):
KOBO_TOKEN=
KOBO_ASSET_UID=
KOBO_BASE_URL=https://kf.kobotoolbox.org
EOF
chmod 600 .env

say "Verifying the seed landed"
supabase db push --dry-run >/dev/null 2>&1 || true
echo "Run this to confirm 141 centres are present:"
echo "  supabase db execute --project-ref $PROJECT_REF \\"
echo "    --query 'select count(*) from centres;'   # (or use the SQL editor)"

cat <<EOF

--------------------------------------------------------------------------
Done. Credentials are in .env (chmod 600, already git-ignored).

Next:
  1. Add your KOBO_TOKEN and KOBO_ASSET_UID to .env
  2. bvl-sync --loop 300
--------------------------------------------------------------------------
EOF
