-- ============================================================
-- The PWA writes to players_clean instead of players
--
-- players_clean holds the cleaned historical registrations (created outside
-- these migrations). To take PWA submissions it needs:
--   1. sl_no to number itself — the PWA runs offline on many phones and
--      cannot pick the next number.
--   2. The same source-agnostic identity as players, so a retried send from
--      the offline queue is recognised instead of duplicated.
--   3. Consent, submission time and team columns.
--   4. Row level security. Before this, the publishable key shipped in the
--      PWA could read every child's record in this table.
--   5. A one-off backfill of team from date of birth and sex.
-- ============================================================

-- ---------- 1. Auto-numbered sl_no ------------------------------------
alter table players_clean alter column sl_no add generated by default as identity;
select setval(pg_get_serial_sequence('players_clean', 'sl_no'),
              (select coalesce(max(sl_no), 0) + 1 from players_clean), false);

-- ---------- 2. Identity for retries -----------------------------------
alter table players_clean add column if not exists source    text;
alter table players_clean add column if not exists source_id text;
create unique index if not exists players_clean_source_uidx
  on players_clean (source, source_id);

-- ---------- 3. New columns --------------------------------------------
alter table players_clean add column if not exists guardian_consent boolean;
alter table players_clean add column if not exists submitted_at     timestamptz;
alter table players_clean add column if not exists team             text;

alter table players_clean drop constraint if exists players_clean_team_known;
alter table players_clean add constraint players_clean_team_known
  check (team is null or team in ('u12_boys', 'u12_girls', 'u16_boys', 'u16_girls'));

-- ---------- 4. Row level security --------------------------------------
-- The secret key (sync, dashboard) bypasses RLS and is unaffected.
alter table players_clean enable row level security;

-- Write-only for the publishable key, as on players: no select policy, so
-- it cannot read back any record.
drop policy if exists "anon can submit registrations" on players_clean;
create policy "anon can submit registrations"
  on players_clean for insert to anon
  with check (
    source = 'pwa'
    and source_id is not null
    and guardian_consent = true
    and char_length(player_name) between 3 and 120
    and dob > current_date - interval '30 years'
    and dob < current_date
  );

-- ---------- 5. Backfill team -------------------------------------------
-- Age today: under 12 -> u12, 12 to 15 -> u16, 16 and over stays null.
-- sex is trimmed/uppercased because the imported data has stray spaces.
update players_clean
set team = case
    when extract(year from age(current_date, dob)) < 12 then 'u12_'
    when extract(year from age(current_date, dob)) < 16 then 'u16_'
  end
  || case upper(trim(sex)) when 'M' then 'boys' when 'F' then 'girls' end
where team is null
  and dob is not null;
