-- Seed: real BVL centres extracted from 'Centre Profile.csv'
insert into centres (centre_code, centre_name, district) values
  ('najowan_sangha_vcc', 'Najowan Sangha VCC', 'Nalbari'),
  ('bapuji_vcc', 'Bapuji VCC', 'Lakhimpur'),
  ('okhas_vcc', 'OKHAS VCC', 'Karbi Anglong'),
  ('karbi_club_vcc', 'Karbi Club VCC', 'Karbi Anglong'),
  ('kardaiguri_vcc', 'Kardaiguri VCC', 'Bajali'),
  ('bhergaon_vcc', 'Bhergaon VCC', 'Bhergaon (BTR)'),
  ('bajali_vcc', 'Bajali VCC', 'Bajali'),
  ('khalihamari_vcc', 'Khalihamari VCC', 'Dhemaji'),
  ('nitaipukhuri_vcc', 'Nitaipukhuri VCC', 'Sivasagar'),
  ('hologuri_rupali_vcc', 'Hologuri Rupali VCC', 'Sivasagar'),
  ('laina_vcc', 'Laina VCC', 'Tinsukia'),
  ('barpeta_vcc', 'Barpeta VCC', 'Barpeta'),
  ('rkvc_jaranigaon_vcc', 'RKVC Jaranigaon VCC', 'Bishwanath'),
  ('pub_dikrong_vcc', 'Pub - Dikrong VCC', 'Lakhimpur'),
  ('cheki_vcc', 'Cheki VCC', 'Bajali'),
  ('howajan_vcc', 'Howajan VCC', 'Bishwanath'),
  ('nakachari_vcc', 'Nakachari VCC', 'Jorhat'),
  ('uzan_barbari_vcc', 'Uzan Barbari VCC', 'Bajali'),
  ('ukhura_vcc', 'Ukhura VCC', 'Kamrup'),
  ('kherbari_vcc', 'Kherbari VCC', 'Kamrup (M)'),
  ('kansiyoli_vcc', 'Kansiyoli VCC', 'Jorhat'),
  ('dulimerh_vcc', 'Dulimerh VCC', 'Dhemaji'),
  ('pragati_vcc', 'Pragati VCC', 'Morigaon'),
  ('lohitmukh_vcc', 'Lohitmukh VCC', 'Bishwanath'),
  ('naharkatia_vcc', 'Naharkatia VCC', 'Dibrugarh'),
  ('sports_hub_hbb', 'Sports HUB, HBB', 'Morigaon'),
  ('suratabori_vcc', 'Suratabori VCC', 'Morigaon'),
  ('mikirbheta_vcc', 'Mikirbheta VCC', 'Morigaon'),
  ('dhekiajuli_vcc', 'Dhekiajuli VCC', 'Lakhimpur'),
  ('besseria_vcc', 'Besseria VCC', 'Sonitpur'),
  ('kuhipat_volleyball_academy', 'Kuhipat Volleyball Academy', 'Morigaon'),
  ('panitola_vcc', 'Panitola VCC', 'Tinsukia'),
  ('aalok_vcc', 'Aalok VCC', 'Dibrugarh'),
  ('kapahera_zone_mneva_vcc', 'Kapahera Zone (MNEVA) VCC', 'Morigaon'),
  ('barapujia_zone_mneva_vcc', 'Barapujia Zone (MNEVA) VCC', 'Morigaon'),
  ('harissinga_vcc', 'Harissinga VCC', 'Udalguri'),
  ('monumoi_vcc', 'Monumoi VCC', 'Jorhat'),
  ('bamgaon_vcc', 'Bamgaon VCC', 'Bishwanath'),
  ('chaturanga_vcc', 'Chaturanga VCC', 'Lakhimpur'),
  ('gelabil_vcc', 'Gelabil VCC', 'Golaghat'),
  ('bokajan_vcc', 'Bokajan VCC', 'Karbi Anglong'),
  ('diburu_vcc', 'Diburu VCC', 'Dibrugarh'),
  ('panibura_vcc', 'Panibura VCC', 'Dibrugarh'),
  ('banmukh_vcc', 'Banmukh VCC', 'Sivasagar'),
  ('bahbari_vcc', 'Bahbari VCC', 'Sonitpur'),
  ('megela_vcc', 'Megela VCC', 'Tinsukia'),
  ('dhamdhama_vcc', 'Dhamdhama VCC', 'Nalbari'),
  ('madhyampur_vcc', 'Madhyampur VCC', 'Golaghat'),
  ('dharamtala_vcc', 'Dharamtala VCC', 'Bajali'),
  ('balitara_vcc', 'Balitara VCC', 'Nalbari'),
  ('teok_vcc', 'Teok VCC', 'Jorhat'),
  ('khopanikuchi_vcc', 'Khopanikuchi VCC', 'Kamrup'),
  ('diamond_vcc', 'Diamond VCC', 'Majuli'),
  ('kamarbandha_vcc', 'Kamarbandha VCC', 'Golaghat'),
  ('muguria_vcc', 'Muguria VCC', 'Bajali'),
  ('borachuba_vcc', 'Borachuba VCC', 'Darrang'),
  ('borpathar_vcc', 'Borpathar VCC', 'Dibrugarh'),
  ('ouphulia_vcc', 'Ouphulia VCC', 'Dibrugarh'),
  ('global_vcc', 'Global VCC', 'Kamrup'),
  ('hatinga_prostuti_vcc', 'Hatinga Prostuti VCC', 'Sonitpur'),
  ('barbari_vcc', 'Barbari VCC', 'Nalbari'),
  ('sagarbera_vcc', 'Sagarbera VCC', 'Charaideo'),
  ('shkhanagug_vcc', 'Shkhanagug VCC', 'Morigaon'),
  ('dhakuakhana_vcc', 'Dhakuakhana VCC', 'Lakhimpur'),
  ('balagaon_vcc', 'Balagaon VCC', 'Barpeta'),
  ('aulachowka_vcc', 'Aulachowka VCC', 'Darrang'),
  ('bamundi_vcc', 'Bamundi VCC', 'Kamrup'),
  ('royal_vtc', 'Royal VTC', 'Kamrup'),
  ('chhaygaon_vcc', 'Chhaygaon VCC', 'Kamrup'),
  ('boko_vcc', 'Boko VCC', 'Kamrup'),
  ('fekelajan_vcc', 'Fekelajan VCC', 'Dibrugarh'),
  ('borkula_vcc', 'Borkula VCC', 'Dibrugarh'),
  ('ghilamara_vcc', 'Ghilamara VCC', 'Lakhimpur'),
  ('dighali_mothwani_vcc', 'Dighali Mothwani VCC', 'Dibrugarh'),
  ('polashjyoti_academy', 'Polashjyoti Academy', 'Dibrugarh'),
  ('dhemaji_vcc', 'Dhemaji VCC', 'Dhemaji'),
  ('jerai_vcc', 'Jerai VCC', 'Tinsukia'),
  ('guwahati_vcc', 'Guwahati VCC', 'Kamrup (M)'),
  ('sapatgram_sports_foundation', 'Sapatgram Sports Foundation', 'Dhuburi'),
  ('hailakandfi_vcc', 'Hailakandfi VCC', 'Hailakandi'),
  ('jalah_vcc', 'Jalah VCC', 'Baksa'),
  ('chhamaria_vcc', 'Chhamaria VCC', 'Kamrup (R)'),
  ('rupjyoti_sangha_garemari', 'Rupjyoti Sangha, Garemari', 'Bajali'),
  ('chaiguri_vcc', 'Chaiguri VCC', 'Lakhimpur'),
  ('tangla_vcc', 'Tangla VCC', 'Udalguri'),
  ('balisatra_vcc', 'Balisatra VCC', 'Kamrup'),
  ('goreswar_vcc', 'Goreswar VCC', 'Tamulpur'),
  ('khalha_vcc', 'Khalha VCC', 'South Kamrup'),
  ('niz_pakowa_suniti_sangha', 'Niz Pakowa Suniti Sangha', 'Nalbari'),
  ('bhehbari_vcc', 'Bhehbari VCC', 'Kamrup (R)'),
  ('rangadaria_vcc', 'Rangadaria VCC', 'Morigaon'),
  ('chabukdhara_vcc', 'Chabukdhara VCC', 'Morigaon'),
  ('ringchnag_vcc', 'Ringchnag VCC', 'Morigaon'),
  ('barapujia_sports_academy', 'Barapujia Sports Academy', 'Nagaon'),
  ('golaghat_vcc', 'Golaghat VCC', 'Golaghat'),
  ('cinnamara_vcc', 'Cinnamara VCC', 'Jorhat'),
  ('natunmati_vcc', 'Natunmati VCC', 'Jorhat'),
  ('deha_vcc', 'Deha VCC', 'Jorhat'),
  ('bodousa_vcc', 'Bodousa VCC', 'Tinsukia'),
  ('natungaon_vcc', 'Natungaon VCC', 'Tinsukia'),
  ('kaliapani_vcc', 'Kaliapani VCC', 'Dibrugarh'),
  ('borbam_vcc', 'Borbam VCC', 'Dibrugarh'),
  ('mathurapur_vcc', 'Mathurapur VCC', 'Charaideo'),
  ('naruathan_vcc', 'Naruathan VCC', 'Dhemaji'),
  ('nemupather_vcc', 'Nemupather VCC', 'Dibrugarh'),
  ('upper_majuli_vcc', 'Upper Majuli VCC', 'Majuli'),
  ('phulbari_vcc', 'Phulbari VCC', 'Lakhimpur'),
  ('lopers_club', 'Lopers Club', 'Bajali'),
  ('sorbhog_vcc', 'Sorbhog VCC', 'Barpeta'),
  ('dihing_gaon_vcc', 'Dihing Gaon VCC', 'Nagaon'),
  ('hazarikapara_vcc', 'Hazarikapara VCC', 'Darrang'),
  ('narengi_vcc', 'Narengi VCC', 'Kamrup (M)'),
  ('nalbari_vcc', 'Nalbari VCC', 'Nalbari'),
  ('migang_vcc', 'Migang VCC', 'Golaghat'),
  ('bechimari_vcc', 'BECHIMARI VCC', 'Darrang'),
  ('center_of_excellence', 'Center of Excellence', 'Kamrup (M)'),
  ('langhin_vcc', 'LANGHIN VCC', 'Karbi Anglong'),
  ('chitralekha_vcc', 'Chitralekha VCC', 'Sonitpur'),
  ('naharani_sports_foundation', 'Naharani Sports Foundation', 'Golaghat'),
  ('gpd_danswrang', 'GPD Danswrang', 'Bishwanath'),
  ('namti_vcc', 'Namti VCC', 'Sivasagar'),
  ('tezpur_vcc', 'Tezpur VCC', 'Sonitpur'),
  ('joypur_dihing', 'Joypur dihing', 'Dibrugarh'),
  ('sarusajai_vcc', 'Sarusajai VCC', 'Kamrup (M)'),
  ('monomoy_vcc', 'Monomoy VCC', 'Jorhat'),
  ('bijuli_club', 'Bijuli club', 'Bongaigaon'),
  ('chandrapur_vcc', 'Chandrapur VCC', 'Kamrup (M)'),
  ('samiran_vcc', 'Samiran VCC', 'Darrang'),
  ('borachuk_vcc', 'Borachuk VCC', 'Bishwanath'),
  ('defalala_vcc', 'Defalala VCC', 'Karimganj'),
  ('simaluguri_vcc', 'Simaluguri VCC', 'Lakhimpur'),
  ('sonai_vcc', 'Sonai VCC', 'Cachar'),
  ('ujani_miri_vcc', 'Ujani miri VCC', 'Lakhimpur'),
  ('barekuri_vcc', 'Barekuri VCC', 'Tinsukia'),
  ('pahumara_vcc', 'Pahumara VCC', 'Lakhimpur'),
  ('hatsingimari_sports_academy', 'Hatsingimari sports academy', 'South Salmara'),
  ('rampur_vcc', 'Rampur VCC', 'Lakhimpur'),
  ('kapa_no1_angkhwrbary', 'Kapa no1 Angkhwrbary', 'Bishwanath'),
  ('dagiapara_vcc', 'Dagiapara VCC', 'Darrang'),
  ('srikona_vcc', 'Srikona VCC', 'Cachar'),
  ('sangsua_vcc', 'Sangsua VCC', 'Jorhat')
on conflict (centre_code) do update set centre_name = excluded.centre_name, district = excluded.district;
